from __future__ import annotations

DOCUMENTED_API_ENDPOINTS: frozenset[tuple[str, str]] = frozenset(
    {
        ("GET", "user.json"),
        ("PUT", "user.json"),
        ("GET", "user_logs.json"),
        ("GET", "user_point_logs.json"),
        ("GET", "sections.json"),
        ("GET", "sections/:section_id.json"),
        ("POST", "sections.json"),
        ("PUT", "sections/:section_id.json"),
        ("DELETE", "sections/:section_id.json"),
        ("GET", "sections/default.json"),
        ("PUT", "sections/sort.json"),
        ("GET", "accounts.json"),
        ("GET", "accounts/:account.json"),
        ("GET", "accounts/:account/:account_id.json"),
        ("GET", "accounts/:account/:account_id/exists.json"),
        ("POST", "accounts/:account.json"),
        ("PUT", "accounts/:account/:account_id.json"),
        ("DELETE", "accounts/:account/:account_id/:section_id.json"),
        ("PUT", "accounts/:account/sort.json"),
        ("GET", "entries.json"),
        ("GET", "entries/:entry_id.json"),
        ("POST", "entries.json"),
        ("PUT", "entries/:entry_id.json"),
        ("PUT", "entries/:entry_ids/:section_id.json"),
        ("DELETE", "entries/:entry_ids/:section_id.json"),
        ("GET", "entries/latest.json"),
        ("GET", "entries/latest_items.json"),
        ("GET", "entries/flow_of_account.json"),
        ("GET", "entries/flow_of_account_id.json"),
        ("GET", "entries/changes_of_account_id.json"),
        ("GET", "entries/changes_of_client.json"),
        ("GET", "entries/changes_of_item.json"),
        ("GET", "entries/account_ids_of_account.json"),
        ("GET", "entries/clients_of_account_id.json"),
        ("GET", "entries/items_of_account_id.json"),
        ("POST", "entries/outside.json"),
        ("POST", "entries/outside_report.json"),
        ("GET", "frequent_items.json"),
        ("GET", "frequent_items/:slot.json"),
        ("GET", "frequent_items/:slot/:item_id.json"),
        ("POST", "frequent_items/:slot.json"),
        ("PUT", "frequent_items/:slot/:item_id.json"),
        ("DELETE", "frequent_items/:slot/:item_id/:section_id.json"),
        ("PUT", "frequent_items/:slot/sort.json"),
        ("GET", "monthly_items.json"),
        ("GET", "monthly_items/slot1.json"),
        ("GET", "monthly_items/slot1/:item_id.json"),
        ("POST", "monthly_items/slot1.json"),
        ("PUT", "monthly_items/slot1/:item_id.json"),
        ("DELETE", "monthly_items/slot1/:item_id/:section_id.json"),
        ("GET", "budget/:account.json"),
        ("PUT", "budget/:account.json"),
        ("PUT", "budget/:account/basic_total.json"),
        ("DELETE", "budget/:account.json"),
        ("GET", "budget_goal.json"),
        ("PUT", "budget_goal.json"),
        ("DELETE", "budget_goal.json"),
        ("GET", "bill.json"),
        ("GET", "bill/:account_id.json"),
        ("GET", "checkcard.json"),
        ("GET", "checkcard/:account_id.json"),
        ("GET", "in_out.json"),
        ("GET", "in_out/:account.json"),
        ("GET", "in_out/:account/:account_id.json"),
        ("GET", "calendar.json"),
        ("GET", "report.json"),
        ("GET", "report/:account.json"),
        ("GET", "report/:account/:account_id.json"),
        ("GET", "report_summary.json"),
        ("GET", "report_summary/:account.json"),
        ("GET", "main/report_customs.json"),
        ("POST", "main/report_customs.json"),
        ("GET", "goal.json"),
        ("PUT", "goal.json"),
        ("GET", "post_it.json"),
        ("GET", "post_it/:post_it_id.json"),
        ("POST", "post_it.json"),
        ("PUT", "post_it/:post_it_id.json"),
        ("DELETE", "post_it/:section_id/:post_it_id.json"),
        ("GET", "messages.json"),
        ("GET", "messages/:opponent_user_id.json"),
        ("POST", "messages.json"),
        ("DELETE", "messages/:opponent_user_id.json"),
        ("GET", "messages/unread.json"),
        ("GET", "bbs.json"),
        ("GET", "bbs/:category.json"),
        ("GET", "bbs/:category/:bbs_id.json"),
        ("POST", "bbs/:category.json"),
        ("PUT", "bbs/:category/:bbs_id.json"),
        ("DELETE", "bbs/:category/:bbs_id.json"),
        ("GET", "bbs/:category/:bbs_id/:comment_id.json"),
        ("POST", "bbs/:category/:bbs_id.json"),
        ("PUT", "bbs/:category/:bbs_id/:comment_id.json"),
        ("DELETE", "bbs/:category/:bbs_id/:comment_id.json"),
        ("POST", "bbs/:category/:bbs_id/:comment_id.json"),
        ("DELETE", "bbs/:category/:bbs_id/:comment_id/:addition_id.json"),
        ("PUT", "bbs/recommandation.json"),
        ("GET", "upload.json"),
        ("POST", "upload.json"),
        ("GET", "notifications.json"),
        ("PUT", "notifications.json"),
    }
)

IMPLEMENTED_API_ENDPOINTS = DOCUMENTED_API_ENDPOINTS


def test_all_documented_api_endpoints_are_tracked() -> None:
    assert IMPLEMENTED_API_ENDPOINTS == DOCUMENTED_API_ENDPOINTS
    assert len(DOCUMENTED_API_ENDPOINTS) == 101
